### ISSUE TITLE
Change the "Search..." placeholder 

### ISSUE THREAD

**Issue by tuttarealstep** [ProticM/vue-gridmultiselect#45]
This is a feature request.
Add the ability to change the "Search..." placeholder, I'm building a multilanguage page and I need to translate also the placeholder.

The best thing is something like the "empty-message" prop.

**Comment by ProticM** [comment]
@tuttarealstep Thank you for using the vue-gridmultiselect and taking the time to make this feature request :)

Yes, this seems like a useful improvement, I will include it in the next release.

**Comment by ProticM** [comment]
The feature has been implemented.

Docs: https://proticm.github.io/vue-gridmultiselect/guide/api.html#searchboxplaceholder

Example usage:

```html
<GridMultiSelect
  search-box-placeholder="My Text"
/>
```
