### ISSUE TITLE
Template item slots not selectable.

### ISSUE THREAD

**Issue by vicentenoriega** [ProticM/vue-gridmultiselect#50]
`    <GridMultiSelect :items="items" item-key="id" item-label="name" v-model="selectedItems" title="Cities">
      <template v-slot:item="{ item }"> TEMPLATE TEST - {{ item.name }} </template>
    </GridMultiSelect>`

`data() {
    return {
      selectedItems: null,
      items: [
        { id: 1, name: "San Francisco", state: "USA" },
        { id: 2, name: "Las Vegas", state: "USA" },
        { id: 3, name: "Washington", state: "USA" },
        { id: 4, name: "Munich", state: "Germany" },
        { id: 5, name: "Berlin", state: "Germany" },
        { id: 6, name: "Rome", state: "Italy" }
      ]
    };
  }`

I tried to use v-slot:item but that makes the items unselectable.

Thanks in advance.

**Comment by ProticM** [comment]
Hi @vicentenoriega. Thanks for using grid multiselect 🙂

I will look into it and let you know about the result.

**Comment by ProticM** [comment]
@vicentenoriega I've found a reason for this. Internally, I use `for` attribute to provide selection functionality. The solution would be to wrap the `slot` with the label, currently is the other way around and due to that this issue is there.

**Comment by ProticM** [comment]
@vicentenoriega I've released a patch (v1.2.2) and the issue should be fixed. Could you check it out and let me know?

**Comment by vicentenoriega** [comment]
@ProticM It's fixed! Thanks very much :+1:
